<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>1717b505-2c41-4e61-85f5-a780ef094f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fc0635ae-17ea-4c60-b095-10eb00d85b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
      <webElementGuid>fbbcf1ce-aa35-4851-aca7-5e9fa17127cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>25db243c-2db0-40dc-bc46-cf595b31a243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>080fdb96-4b67-423b-ac32-5cd9f907ed14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>น้ำไม</value>
      <webElementGuid>efb1f11d-5973-40eb-af7b-7e60e0db4023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;c1 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;c2 col&quot;]/form[1]/textarea[@class=&quot;rounded&quot;]</value>
      <webElementGuid>aabef470-a6ce-45c8-a5c2-c0bf42897bcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='']</value>
      <webElementGuid>e835a790-bfca-48c2-8c82-971ee85e5360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/textarea</value>
      <webElementGuid>f511ed53-aa2c-4f24-8f6e-8b811734015a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แจ้งรายละเอียดปัญหา'])[1]/following::textarea[1]</value>
      <webElementGuid>4f37cc51-e2df-4358-a432-38611948569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รูปภาพสิ่งของชำรุด'])[1]/following::textarea[1]</value>
      <webElementGuid>78a1ff3f-a5e3-41c7-8162-ff8ce4544b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ยืนยัน'])[1]/preceding::textarea[1]</value>
      <webElementGuid>21077785-09c3-4cd9-ace9-6920e4814389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='น้ำไม']/parent::*</value>
      <webElementGuid>0df2f3f4-b7cd-4a6b-937b-8d7b000fca15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3c9d052e-6b2e-464e-90dd-c4cacbd42c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'น้ำไม' or . = 'น้ำไม')]</value>
      <webElementGuid>81161f5a-e354-4aeb-9e93-9f80fcf19336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
